### ISSUE TITLE
Weird shadow on blocks

### ISSUE THREAD

**Issue by Gamerbolts** [Flenix/FlenixRoads#1]
Hi. I was playing around with your mod, I originally had road stuff, but liked the customizing options in FlexisRoads. So now I am using both of the mods. But when I was going around placing the roads. I get weird shadows on blacks that don't look natural. I am not sure if it may be optifine or not but here is an image without the block placed

http://imgur.com/a/NAPe0

and with the block placed

http://imgur.com/a/DZgV1

If i break the block next to it it drops the shadow. and that block is the same height as the blocks to the right. Not sure if you can know what the issue is by this. But hoping you can help. Thanks!

**Comment by Fureniku** [comment]
Have you got smooth lighting on? If so it might just be a bug I've not found/got around to fixing yet. Lighting on roads has proved to be a real pain to fix...
Date: Sun, 11 Sep 2016 13:54:27 -0700

**Comment by Gamerbolts** [comment]
I had smooth lighting Off actually. turned it on and everything worked :)
