### ISSUE TITLE
Game crashes when destroying tar distillery, other issues

### ISSUE THREAD

**Issue by Methlon** [Flenix/FlenixRoads#12]
Tar distillery isn't producing tar past 1000 is also an issue, but I posted in that thread.
Tar Factory doesn't 'do anything at all, and won't take tar, which the tar buckets want to come from jurassicraft. (Many mods I have.)

When frustrated, and trying to move the currently fuel burning distillery, to the left of the factory (which do not work together) the game crashes upon blocks destruction..  Server keeps running, but the client blacks out into oblivion, and I have to end java through the task manager to stop the process.

Thanks for your time.

**Comment by Fureniku** [comment]
Both the not creating tar and the crash are fixed for next release. I'll look into adding support for tars from other mods too and try and get that included, but can't promise it'll be in for the next release.
