### ISSUE TITLE
Game crashes when selecting handicapped icon

### ISSUE THREAD

**Issue by MinecraftKen59** [Flenix/FlenixRoads#15]
The game crashes when you select the handicap icon and put in hotbar. Doesn't matter what color. I have to delete the mod and restart. Then reload game. Speaking of color, how is the BLUE update coming?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  ZarakLIBCore (ZarakLIB.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/17/19 8:38 PM
Description: Ticking player

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block furenikusroads:white_wheelchair_icon, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at com.silvaniastudios.roads.blocks.IconPaintBlock.func_176203_a(IconPaintBlock.java:44)
	at mods.railcraft.common.util.inventory.InvTools.getBlockStateFromStack(InvTools.java:488)
	at mods.railcraft.common.blocks.tracks.TrackTools.isRailBlock(TrackTools.java:73)
	at mods.railcraft.common.advancements.criterion.TrackItemPredicate.func_192493_a(TrackItemPredicate.java:66)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Instance.func_192265_a(SourceFile:104)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:149)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69)
	at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:972)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at com.silvaniastudios.roads.blocks.IconPaintBlock.func_176203_a(IconPaintBlock.java:44)
	at mods.railcraft.common.util.inventory.InvTools.getBlockStateFromStack(InvTools.java:488)
	at mods.railcraft.common.blocks.tracks.TrackTools.isRailBlock(TrackTools.java:73)
	at mods.railcraft.common.advancements.criterion.TrackItemPredicate.func_192493_a(TrackItemPredicate.java:66)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Instance.func_192265_a(SourceFile:104)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:149)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69)
	at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:972)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 3453
	Entity Name: MinecraftKen05
	Entity's Exact location: -438.23, 63.00, -3183.26
	Entity's Block location: World: (-439,63,-3184), Chunk: (at 9,3,0 in -28,-199; contains blocks -448,0,-3184 to -433,255,-3169), Region: (-1,-7; contains chunks -32,-224 to -1,-193, blocks -512,0,-3584 to -1,255,-3073)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: August
	All players: 1 total; [EntityPlayerMP['MinecraftKen05'/3453, l='August', x=-438.23, y=63.00, z=-3183.26]]
	Chunk stats: ServerChunkCache: 881 Drop: 0
	Level seed: 175040559011451460
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":36,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":false,"useMansions":true,"useRavines":false,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":false,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":3,"dirtSize":33,"dirtCount":10,"dirtMinHeight":50,"dirtMaxHeight":256,"gravelSize":11,"gravelCount":5,"gravelMinHeight":177,"gravelMaxHeight":256,"graniteSize":1,"graniteCount":0,"graniteMinHeight":0,"graniteMaxHeight":0,"dioriteSize":1,"dioriteCount":0,"dioriteMinHeight":0,"dioriteMaxHeight":0,"andesiteSize":1,"andesiteCount":0,"andesiteMinHeight":0,"andesiteMaxHeight":0,"coalSize":17,"coalCount":20,"coalMinHeight":16,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":16,"ironMaxHeight":127,"goldSize":9,"goldCount":2,"goldMinHeight":16,"goldMaxHeight":80,"redstoneSize":8,"redstoneCount":6,"redstoneMinHeight":16,"redstoneMaxHeight":30,"diamondSize":8,"diamondCount":2,"diamondMinHeight":16,"diamondMaxHeight":80,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (140,64,188), Chunk: (at 12,4,12 in 8,11; contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7609811 game time, 7609811 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3204562224 bytes (3056 MB) / 8858370048 bytes (8448 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 93
	FML: MCP 9.42 Powered by Forge 14.23.5.2831 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                | Source                                                                 | Signature                                |
	|:------ |:----------------------- |:---------------------- |:---------------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                 | minecraft.jar                                                          | None                                     |
	| LCHIJA | mcp                     | 9.42                   | minecraft.jar                                                          | None                                     |
	| LCHIJA | FML                     | 8.0.99.99              | forge-1.12.2-14.23.5.2831.jar                                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2831           | forge-1.12.2-14.23.5.2831.jar                                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | obfuscate               | 0.2.6                  | minecraft.jar                                                          | None                                     |
	| LCHIJA | imsm                    | 1.12                   | [1.12]InstantMassiveStructuresMod.jar                                  | None                                     |
	| LCHIJA | movillages              | 1.5.4                  | [1.12]MoVillages-1.5.4.jar                                             | None                                     |
	| LCHIJA | mts                     | 14.3.1                 | Immersive+Vehicles-1.12.2-14.3.1.jar                                   | None                                     |
	| LCHIJA | mtsaircooled            | 1.0.0                  | Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-BETA+1.0.0.jar                     | None                                     |
	| LCHIJA | engineersdecor          | 1.0.11-b1              | engineersdecor-1.12.2-1.0.11-b1.jar                                    | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | engineerstools          | 1.0.1                  | engineerstools-1.12.2-1.0.1.jar                                        | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | jei                     | 4.15.0.268             | jei_1.12.2-4.15.0.268.jar                                              | None                                     |
	| LCHIJA | forestry                | 5.8.2.384              | forestry_1.12.2-5.8.2.384.jar                                          | None                                     |
	| LCHIJA | railcraft               | 12.0.0                 | railcraft-12.0.0.jar                                                   | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | redstoneflux            | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar                                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                | 4.6.3                  | CoFHCore-1.12.2-4.6.3.27-universal.jar                                 | None                                     |
	| LCHIJA | cofhworld               | 1.3.1                  | CoFHWorld-1.12.2-1.3.1.7-universal.jar                                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalfoundation       | 2.6.3                  | ThermalFoundation-1.12.2-2.6.3.27-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | immersiveengineering    | 0.12-89                | ImmersiveEngineering-0.12-89.jar                                       | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | alternatingflux         | 0.12.2-2               | alternatingflux-0.12.2-2.jar                                           | None                                     |
	| LCHIJA | craftstudioapi          | 1.0.0                  | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar                     | None                                     |
	| LCHIJA | animania                | 1.6.2                  | animania-1.12.2-1.6.2.jar                                              | None                                     |
	| LCHIJA | applecore               | 3.2.0                  | AppleCore-mc1.12.2-3.2.0.jar                                           | None                                     |
	| LCHIJA | baubles                 | 1.5.2                  | Baubles-1.12-1.5.2.jar                                                 | None                                     |
	| LCHIJA | atum                    | 2.0.11                 | Atum-1.12.2-2.0.11.jar                                                 | None                                     |
	| LCHIJA | quark                   | r1.6-177               | Quark-r1.6-177.jar                                                     | None                                     |
	| LCHIJA | autoreglib              | 1.3-32                 | AutoRegLib-1.3-32.jar                                                  | None                                     |
	| LCHIJA | get_back_to_home        | 1.5                    | BackToHome-1.5.jar                                                     | None                                     |
	| LCHIJA | coordinatesplusmod      | 1.12.0_004             | Batty's+Coordinates+PLUS+Mod+for+Forge-1.12.0_004.jar                  | None                                     |
	| LCHIJA | betteranimalsplus       | 7.0.1                  | betteranimalsplus-1.12.2-7.0.1.jar                                     | None                                     |
	| LCHIJA | unuparts                | 2.0.2                  | UNU+Parts+Pack+[MTS]+1.10.2-14.0.0-2.0.2.jar                           | None                                     |
	| LCHIJA | btcivil                 | 2.1.0                  | BlackThorne+Civilian+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-2.1.0.jar | None                                     |
	| LCHIJA | car                     | 1.2.12                 | car-1.12.2-1.2.12.jar                                                  | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                                               | None                                     |
	| LCHIJA | charm                   | 1.12.2-1.3.2           | Charm-1.12.2-1.3.2.jar                                                 | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353              | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | coffeespawner           | 1.0.2                  | CoffeeSpawner-1.12-1.0.2.jar                                           | None                                     |
	| LCHIJA | coffeework              | 1.2.9                  | CoffeeWorkshop_V1.2.9_MC1.12.2.jar                                     | None                                     |
	| LCHIJA | storagedrawers          | 1.12-5.3.5             | StorageDrawers-1.12.2-5.3.8.jar                                        | None                                     |
	| LCHIJA | compactdrawers          | 1.12.2-1.0.5.121       | CompactDrawers-1.12.2-1.0.5.121.jar                                    | None                                     |
	| LCHIJA | customspawner           | 3.11.4                 | Custom-Mob-Spawner-Mod-1.12.2.jar                                      | None                                     |
	| LCHIJA | mocreatures             | 12.0.5                 | DrZharks+MoCreatures+Mod-12.0.5.jar                                    | None                                     |
	| LCHIJA | dynamictrees            | 1.12.2-0.9.3           | DynamicTrees-1.12.2-0.9.3.jar                                          | None                                     |
	| LCHIJA | engineersdoors          | 0.8.0                  | engineers_doors-1.12.2-0.8.0.jar                                       | None                                     |
	| LCHIJA | enhancedfarming         | 1.1.3                  | Enhanced-Farming-1.12.2.jar                                            | None                                     |
	| LCHIJA | forgelin                | 1.8.3                  | Forgelin-1.8.3.jar                                                     | None                                     |
	| LCHIJA | furenikusroads          | 1.0.3                  | Fureniku's+Roads-1.0.2.1.jar                                           | None                                     |
	| LCHIJA | futureminecraf          | 1.2.1.1                | FutureVersionsV1.2.1.1.jar                                             | None                                     |
	| LCHIJA | immersivepetroleum      | 1.1.9                  | immersivepetroleum-1.12.2-1.1.9.jar                                    | None                                     |
	| LCHIJA | immersiveposts          | 0.1.2                  | ImmersivePosts-0.1.2.jar                                               | 0ba25d8c0ec23537afc6db926e1ea764335a33b1 |
	| LCHIJA | industrialrenewal       | 0.12.2                 | IndustrialRenewal_1.12.2-0.12.2.jar                                    | None                                     |
	| LCHIJA | ism                     | 2.6.1 MC-1.12.2        | ism-2.6.1 MC-1.12.2.jar                                                | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT  | malisiscore-1.12.2-6.5.1.jar                                           | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                                          | None                                     |
	| LCHIJA | joypadsplitscreenmod    | 1.12.0-0.22            | MCJoypad-Mod-1.12.2.jar                                                | None                                     |
	| LCHIJA | melvinssignpack         | 1.0.0                  | Melvins_Simple_Sign_Pack-Release-0.1.0.jar                             | None                                     |
	| LCHIJA | moarboats               | 4.1.2.1                | moarboats-1.12.2-4.1.2.1.jar                                           | None                                     |
	| LCHIJA | bluprium_mod            | 1.8                    | modid-1.8.jar                                                          | None                                     |
	| LCHIJA | modroadworksreborn      | 0.0.3                  | modroadworksreborn-0.0.3.jar                                           | None                                     |
	| LCHIJA | more_blocks             | 1.12.2                 | more-blocks+5.2.jar                                                    | None                                     |
	| LCHIJA | mtsofficialpack         | 11.0.0                 | MTS_Official_Pack_V11.jar                                              | None                                     |
	| LCHIJA | zaraklib                | 0.0.4                  | ZarakLIB.jar                                                           | None                                     |
	| LCHIJA | multibags               | 0.0.4                  | MultiBags-0.0.5.jar                                                    | None                                     |
	| LCHIJA | naturescompass          | 1.5.1                  | NaturesCompass-1.12.2-1.5.1.jar                                        | None                                     |
	| LCHIJA | nei                     | 2.4.2                  | NotEnoughItems-1.12.2-2.4.2.240-universal.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | orecontrol              | 0.4.3                  | orecontrol-1.12.2-0.4.3.jar                                            | None                                     |
	| LCHIJA | prefab                  | 1.3.0.26               | prefab-1.3.0.26.jar                                                    | None                                     |
	| LCHIJA | reptilemod              | 3.8.4                  | reptilemod-1.12.2-3.8.4-89.jar                                         | None                                     |
	| LCHIJA | sgcraft                 | 1.13.2                 | SGCraft-2.0.0.jar                                                      | None                                     |
	| LCHIJA | simplylight             | 1.12.2-0.8.6           | simplylight-1.12.2-0.8.6.jar                                           | None                                     |
	| LCHIJA | soviet                  | 0.4 The Biggest Update | Soviet+Mod-0.4.jar                                                     | None                                     |
	| LCHIJA | storagedrawersextra     | @VERSION@              | StorageDrawersExtras-1.12-3.1.0.jar                                    | None                                     |
	| LCHIJA | storagedrawersunlimited | 1.12.2-1.3.0           | StorageDrawersUnlimited-1.12.2-1.3.0.jar                               | None                                     |
	| LCHIJA | theexpandedsignspack    | 1.0.1                  | The_Expanded_Signs_Pack-1.0.1.jar                                      | None                                     |
	| LCHIJA | thermaldynamics         | 2.5.5                  | ThermalDynamics-1.12.2-2.5.5.21-universal.jar                          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | vanillaexpansion        | 0.1 - Beta             | Vanilla+Expansion+0.1+-+Beta.jar                                       | None                                     |
	| LCHIJA | vtt                     | 0.6.4                  | VillagerTrades-1.12-0.6.4.jar                                          | None                                     |
	| LCHIJA | flymod                  | 1.0                    | walaryneflymod-1.12.X-1.0.1.1.jar                                      | None                                     |
	| LCHIJA | wooltostring            | 1.12.2                 | WoolToString-1.12.2-1.0.0.jar                                          | None                                     |
	| LCHIJA | nofog                   | 1.12.2-1.12.2-1.0.3.0  | NoFog-1.12.2b3.jar                                                     | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
	| LCHIJA | vt                      | 1.12.2-1.5.3           | VanillaTweaks-1.12.2-1.5.3.jar                                         | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ZarakLIBCore (ZarakLIB.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CharmLoadingPlugin (Charm-1.12.2-1.3.2.jar)
  svenhjol.charm.base.CharmClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MinecraftKen05'/3453, l='August', x=-438.23, y=63.00, z=-3183.26]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Fureniku** [comment]
I have seen issues with railcraft before, but not this one. Railcraft requires an unstable Forge version which I dont yet support, although I'm not sure the exact changes between the stable build and the one they use.

Could you try using the recommended Forge and tell me if this still happens please? Also, is it only when placing the line as a direct block, or does it happen when using the paint gun as well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MinecraftKen59** [comment]
Thanks for the quick response. I was able to use the paint gun and it worked. Appreciate it. 
 
-----Original Message-----

**Comment by Fureniku** [comment]
The core problem from this is fixed in 1.1, so closing this issue now.
