### ISSUE TITLE
Disable snow on layered blocks

### ISSUE THREAD

**Issue by slava110** [Flenix/FlenixRoads#16]
I mean blocks like tarmac and sidewalk. Looks weird.
![2019-10-29_20 38 32](https://user-images.githubusercontent.com/26705162/67793587-2b47c500-fa8c-11e9-8495-8c8f58443f1a.png)

**Comment by Fureniku** [comment]
I feel like this is a nicer solution:
![image](https://user-images.githubusercontent.com/856762/71564615-b993f380-2a9b-11ea-8ba1-8d9307d056a5.png)

However, I will add a config option to prevent snow from settling on roads for people who still might not want it (as this will have the same hitbox caveat that lines do)

Open to feedback before I close the issue
