### ISSUE TITLE
[Crash] [Compat] LittleTiles compat issue

### ISSUE THREAD

**Issue by slava110** [Flenix/FlenixRoads#18]
ForgeVersion: 14.23.5.2847
Fureniku's Roads: 1.0.2.1
LittleTiles: 1.5.0-pre171 (crash on pre175 too)

Steps to reproduce:
1. Take the LittleGrabber (littletiles:grabber)
2. Try to configure LittleGrabber (with C key by default)
3. Crash

Crash Report:
[crash-2019-11-03_14.41.51-client.txt](https://github.com/Fureniku/Furenikus-Roads/files/3801641/crash-2019-11-03_14.41.51-client.txt)

**Comment by Fureniku** [comment]
This should be fixed as part of a larger issue in 1.1
