### ISSUE TITLE
Server with mod crashes when a player has the crosswalk in their inventoru

### ISSUE THREAD

**Issue by EnderHawkeye** [Flenix/FlenixRoads#22]
As the title implies, a server that I run has the mod installed and when a player has the crosswalk from the mod in their inventory(the player grabs it from creative, they had it in their inventory and tried to join), it crashes the server

**Comment by Fureniku** [comment]
This is a known bug, but should have been fixed with the 1.1 beta I released a little while ago.
Are you getting this on the 1.1 beta, or the 1.0 release?
