### ISSUE TITLE
Game crashes when destroying paint filler with pickaxe with paint in it

### ISSUE THREAD

**Issue by Esconomics** [Flenix/FlenixRoads#23]
https://pastebin.com/fcNbpe2p

That is my crash log. On my server for a modpack I am working on, one of my testers crashed when trying to break the filler with a pickaxe. I recreated the same situation in SP while crashing myself. It does NOT crash when it is empty. I assume that this is directly related to the issue someone else posted (https://github.com/Fureniku/Furenikus-Roads/issues/12). Is this something fixable for you or do I need to remove this mod from my pack? Thank you very much for taking the time to look into this.

**Comment by Fureniku** [comment]
Fixed for next release :)
