### ISSUE TITLE
World Crashing: Ticking block entity

### ISSUE THREAD

**Issue by lancce-Wolf** [Flenix/FlenixRoads#30]
heyo,
so i was playing with this mod and had quite the fun time setting up all the machines and automate them partially, got some roads going and started to use the paint gun and the paint mixer machine. i added a vanilla hopper above the paint mixer and a chest that was filled with the necessary dies (white, yellow and red) but after a short moment my server just crashed and now when ever the mod is installed it crashes. i'll include the crash log here.
[crash-2020-08-24_22.25.23-server.txt](https://github.com/Fureniku/Furenikus-Roads/files/5120414/crash-2020-08-24_22.25.23-server.txt)

what i tried so far was to simply remove the mod > start server > confirmed the start with the missing blocks (/fml confirm) > was able to join > saved and stopped > added the mod back in > started again but same problem even though the stuff from this mod should be gone. server starts fine without the mod but it crashes if its installed.

is there any way to fix this?
thanks in advance

EDIT: it seems to give a different error after i tried to remove the hopper while the mod was uninstalled and when i restarted the server with the mod installed: 
[crash-2020-08-24_22.52.14-server.txt](https://github.com/Fureniku/Furenikus-Roads/files/5120427/crash-2020-08-24_22.52.14-server.txt)

**Comment by Fureniku** [comment]
Hmm, I'm not entirely sure what's causing this. The second log doesn't actually mention Roads at all - do you have any mods installed that tweak how hoppers work? (I know some performance fixes modify them).

If not, can you try to recreate the problem with just Roads installed, and see if it still happens? Additionally, update to 1.1.8 when it's released shortly, and set the debug option in the config to 1. Then, if it crashes, please include the full game log (not just the crash log) as I've added some debug right before this crash happens which might help me pinpoint it.

Thanks!

**Comment by stiderspace** [comment]
i have experienced this problem too. it seems that as soon as the paint mixer machine is full of a dye and the hopper trys to put in more it causes a ticking block entity, that will basically corrupt your world.

i did get this debug from your mod.
`[15:47:35] [Server thread/INFO] [STDOUT]: [com.silvaniastudios.roads.FurenikusRoads:debug:179]: [Fureniku's Roads] [#30] Paint filler insertItem called, slot: 1, stackBone Meal x1`

and looking at your code, slot 1 is the paint gun slot not a dye slot

i just tryed something at the end of the insertStack of your PaintFillerStackHandler you try to insert an item into a slot even if all the checks fail. just changing 

`return super.insertItem(slot, stack, simulate);` on line 63  of the PaintFillerStackHandler fixed this
to 
`return stack;`

 fixed this issue. hope this helps 😃

**Comment by CreepCoder** [comment]
You can open the world in MCEdit to delete the hopper manually. This will fix your world. @stiderspace  did some great research, but this reaction might be a bit late for your case.

**Comment by Fureniku** [comment]
Fixed in 1.1.9
