### ISSUE TITLE
Paints don't show up in JEI menu

### ISSUE THREAD

**Issue by Josh65-2201** [Flenix/FlenixRoads#32]
*Versions:*
Minecraft:1.12.2
Forge 14.23.5.2854
Mod: 1.1.7

**Comment by Fureniku** [comment]
This is by design, as they take up a LOT of space (multiple pages) and in survival, they were confusing as you should really use the paint gun.

If it's needed I can add a config option to show them though

**Comment by Josh65-2201** [comment]
Ok a config option would be nice

**Comment by Fureniku** [comment]
Config is added in 1.1.8
