### ISSUE TITLE
My game and my server crash when i start up

### ISSUE THREAD

**Issue by RezaJawaheri** [Flenix/FlenixRoads#38]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MDECore-Core (mdecore-1.12-1.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.7.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 2/18/21 8:00 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:1002)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1391_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:1002)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1391_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 971134912 bytes (926 MB) / 3052404736 bytes (2911 MB) up to 6800539648 bytes (6485 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7296m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 112 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                           | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                    | None                                     |
	| LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ivtoolkit                         | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCH   | micdoodlecore                     |                          | minecraft.jar                                    | None                                     |
	| LCH   | foamfixcore                       | 7.7.4                    | minecraft.jar                                    | None                                     |
	| LCH   | obfuscate                         | 0.4.2                    | minecraft.jar                                    | None                                     |
	| LCH   | securitycraft                     | v1.8.20.2                | [1.12.2]+SecurityCraft+v1.8.20.2.jar             | None                                     |
	| LCH   | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| LCH   | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCH   | asmodeuscore                      | 0.0.17                   | AsmodeusCore-1.12.2-0.0.17.jar                   | None                                     |
	| LCH   | mdecore                           | 1.12-1.1                 | mdecore-1.12-1.1.jar                             | None                                     |
	| LCH   | autooredictconv                   | 1.12-1.0.1               | autooredictconv-1.12-1.0.1.jar                   | None                                     |
	| LCH   | battletowers                      | 1.6.5                    | BattleTowers-1.12.2.jar                          | None                                     |
	| LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | bonsaitrees                       | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                       | None                                     |
	| LCH   | botania                           | r1.10-363                | Botania r1.10-363.jar                            | None                                     |
	| LCH   | buildinggadgets                   | 2.8.4                    | BuildingGadgets-2.8.4.jar                        | None                                     |
	| LCH   | carryon                           | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                     | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCH   | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCH   | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
	| LCH   | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                         | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar            | None                                     |
	| LCH   | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar           | None                                     |
	| LCH   | concrete                          | 1.3                      | concrete-1.3.jar                                 | None                                     |
	| LCH   | controlling                       | 3.0.10                   | Controlling-3.0.10.jar                           | None                                     |
	| LCH   | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.586.jar                | None                                     |
	| LCH   | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.586.jar                | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.586.jar                | None                                     |
	| LCH   | doggytalents                      | 1.15.1.6                 | DoggyTalents-1.12.2-1.15.1.6.jar                 | None                                     |
	| LCH   | dungeontactics                    | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar                 | None                                     |
	| LCH   | durabilityviewer                  | 1.6                      | DurabilityViewer-1.12-forge14.21.1.2387-1.6.jar  | None                                     |
	| LCH   | elevatorid                        | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                    | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                      | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar   | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar    | None                                     |
	| LCH   | enderio                           | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderiointegrationtic             | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderiobase                       | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderioconduits                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderiointegrationforestry        | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCH   | twilightforest                    | 3.11.1020                | twilightforest-1.12.2-3.11.1020-universal[1].jar | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LCH   | enderiointegrationticlate         | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderiomachines                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderiopowertools                 | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                        | None                                     |
	| LCH   | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCH   | fastfurnace                       | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                     | None                                     |
	| LCH   | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                            | None                                     |
	| LCH   | fastbench                         | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                   | None                                     |
	| LCH   | foamfix                           | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                       | None                                     |
	| LCH   | furenikusroads                    | 1.1.9                    | Fureniku's+Roads-1.1.9.jar                       | None                                     |
	| LCH   | cfm                               | 6.3.1                    | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCH   | galacticraftcore                  | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar            | None                                     |
	| LCH   | galacticraftplanets               | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar        | None                                     |
	| LCH   | galaxyspace                       | 2.0.14                   | GalaxySpace-1.12.2-2.0.14.jar                    | None                                     |
	| LCH   | gravestone                        | 1.10.1                   | gravestone-1.10.1.jar                            | None                                     |
	| LCH   | cgm                               | 0.15.3                   | guns-0.15.3-1.12.2.jar                           | None                                     |
	| LCH   | harvest                           | 1.12-1.2.8-25            | Harvest-1.12-1.2.8-25.jar                        | None                                     |
	| LCH   | hbm                               | hbm-1.4.0A-1.12.2        | hbm-1.4.1a.jar                                   | None                                     |
	| LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCH   | icbmclassic                       | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                 | None                                     |
	| LCH   | mts                               | 19.14.0                  | Immersive+Vehicles-1.12.2-19.14.0 (1).jar        | None                                     |
	| LCH   | infernalmobs                      | 1.7.6                    | InfernalMobs-1.12.2.jar                          | None                                     |
	| LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCH   | jeiintegration                    | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                  | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LCH   | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCH   | lootbags                          | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                      | None                                     |
	| LCH   | mcwbridges                        | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                   | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                    | None                                     |
	| LCH   | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar          | None                                     |
	| LCH   | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar               | None                                     |
	| LCH   | stevekung's_lib                   | 1.1.7                    | SteveKunG's-Lib-1.12.2-1.1.7.jar                 | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | moreplanets                       | 2.1.13                   | More-Planets-1.12.2-2.1.13-GC261.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | moreoverlays                      | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                 | None                                     |
	| LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCH   | mtsofficialpack                   | 18.0.0                   | MTS_Official_Pack_V18.jar                        | None                                     |
	| LCH   | recipehandler                     | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar            | None                                     |
	| LCH   | oretweaker                        | 1.0.2-1.12.0             | Ore Tweaker-1.0.2-1.12.0.jar                     | None                                     |
	| LCH   | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                  | None                                     |
	| LCH   | patchouli                         | 1.0-21                   | Patchouli-1.0-21.jar                             | None                                     |
	| LCH   | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCH   | reccomplex                        | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                     | None                                     |
	| LCH   | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCH   | simpleoregen                      | 4.3.4                    | SimpleOreGeneration-4.3.4 mc 1.12.2.jar          | None                                     |
	| LCH   | spartanshields                    | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                  | None                                     |
	| LCH   | spartanweaponry                   | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar            | None                                     |
	| LCH   | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar   | None                                     |
	| LCH   | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                               | None                                     |
	| LCH   | tramplestopper                    | 1.2.0.4                  | tramplestopper-1.12.2-1.2.0.5-universal.jar      | None                                     |
	| LCH   | treechopper                       | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
	| LCH   | vehicle                           | 0.44.1                   | vehicle-mod-0.44.1-1.12.2.jar                    | None                                     |
	| LCH   | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| LCH   | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| LCH   | waddles                           | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                         | None                                     |
	| LCH   | waystones                         | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                       | None                                     |
	| LCH   | xpfromharvest                     | 1.2.0                    | XPFromHarvest-1.12.2-1.2.0.jar                   | None                                     |
	| LCH   | xpbook                            | v2.0                     | xptome-1.12.2-v2.0.jar                           | None                                     |
	| LCH   | thebetweenlands                   | 3.6.2                    | TheBetweenlands-3.6.2-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UD    | mdecore-core                      | 1.0                      | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MDECore-Core (mdecore-1.12-1.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.7.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/Reza/Documents/Curse/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**Comment by Fureniku** [comment]
You have too many block IDs in use; this isn't an error specific to Roads, but I'm guessing Roads was just your most recent addition which pushed it over the edge.

Apparently, mods like this can fix it: https://www.curseforge.com/minecraft/mc-mods/notenoughids but I've not tried or had reason to use them personally.
