### ISSUE TITLE
Crash when emptying machines with buckets.

### ISSUE THREAD

**Issue by Xavienth** [Flenix/FlenixRoads#42]
As seen in #31, there is a crash caused by emptying any machine with a bucket. This only occurs when the machine contains 1000 mB of fluid. This is because in the code, the fluid is removed from the machine before it is added to the bucket. This causes a null pointer because in order to fill the bucket you reference the fluid that is in the machine.
I have confirmed that changing the order of this process fixes the bug.

**Comment by Fureniku** [comment]
Fixed for 1.2
