### ISSUE TITLE
[Suggestion] Do not consume bucket contents in creative mode.

### ISSUE THREAD

**Issue by Xavienth** [Flenix/FlenixRoads#45]
Many other mods allow, for example, continuously adding water by repeatedly right clicking with a water bucket in creative mode without having to refill it. The machines in this mod consume the bucket contents regardless of game mode. It would be helpful if this were not the case in creative mode.

**Comment by Fureniku** [comment]
Implemented for 1.2. Putting a bucket of fluid into the machine will not consume the bucket. Using an empty bucket on the machine will not consume the empty bucket, but will give you a bucket of fluid and drain the machine as normal.
