### ISSUE TITLE
Serene Seasons snow-melting compatibility.

### ISSUE THREAD

**Issue by Xavienth** [Flenix/FlenixRoads#46]
Serene Seasons implements seasons, so at one point in time it can snow, and at another the snow can melt. Because when it snows on the roads it turns into Fureniku snow, it doesn't melt in the summer and must be manually cleared.

**Comment by Fureniku** [comment]
This looks like I'll need to add direct support for SS. I can look into it but it'll be another low priority issue for now. In the short term you can set "snowOnRoads" to false in the config to disable snow settling on roads at all
