### ISSUE TITLE
Concrete And Road Full blocks texture bug

### ISSUE THREAD

**Issue by PDabro** [Flenix/FlenixRoads#47]
Full and slab blocks have weird x-ray texture bug when block is places on top of it. Also I can't place doors or slabs etc. Please make those texture as transparent blocks to get rid of this weird issue. 
![2021-05-27_16 53 14](https://user-images.githubusercontent.com/12714045/119849015-924d8a00-bf0c-11eb-9d66-4e562ada5e92.png)
![2021-05-27_16 56 53](https://user-images.githubusercontent.com/12714045/119849024-937eb700-bf0c-11eb-95b3-bf54ca11fddc.png)

**Comment by Fureniku** [comment]
This has been fixed in the 1.2 beta available on Curseforge. Please either update to the beta or wait for the full release.

**Comment by PDabro** [comment]
Okay Imma look up for updates, also concrete walls have weird hit-boxes just to let you know.
