### ISSUE TITLE
[Suggestion] Barriers that can't be jumped above

### ISSUE THREAD

**Issue by Monniasza** [Flenix/FlenixRoads#48]
I'm building a city with villagers in Minecraft. To prevent villagers from going onto roads, I've put concrete edge barriers. But villagers can jump over the barrier, defeating the purpose.
I suggest two new barriers:
Super Tall Guardrail and Super Tall Glass Barrier - 1.5m height from ground to top

**Comment by Fureniku** [comment]
I'm not at my computer to check currently but I think there's a config
option for the barrier height, that defaults to 1 block but can be changed
to 1.5.

If it's not there yet it certainly will be in the next version :) it
affects all barriers though

**Comment by Monniasza** [comment]
There's no config option yet.

**Comment by Fureniku** [comment]
Added in 1.2
