### ISSUE TITLE
[Suggestion] Diagonal lines and lines that do not connect

### ISSUE THREAD

**Issue by Monniasza** [Flenix/FlenixRoads#49]
I'd like to have diagonal lines to complete the diagonal road system. I've tried diagonal roads, but the only lines (diagonal arrow line) don't connect well with the only compatible connector (arrow connector)
Connection made by arrow connector (expected | actual):
```
  /   #   |/
 O    #   O
 |    #   |
```

Suggested content:
- NC straight lines
- 45° lines
- Diagonal -- axis-aligned connectors (2 types)
- Diagonal barriers
- Diagonal short lines

**Comment by Fureniku** [comment]
This is already planned for the next release. The paint isn't implemented yet but diagonal roads themselves are in the betas on Discord: https://discord.gg/BPzpQk2
