### ISSUE TITLE
Limestone Dust Texture

### ISSUE THREAD

**Issue by ghost** [Flenix/FlenixRoads#5]
Mining a piece of limestone drops the dust, which doesn't appear to have the texture.

BTW - Beautiful mod, thank you.

![2019-03-04_21 30 24](https://user-images.githubusercontent.com/38612528/53776705-cddf8200-3ec4-11e9-8947-3a430e98cc8a.png)

**Comment by ionutsoran** [comment]
I can confirm this on Fureniku's Roads 1.0 for 1.12.2

**Comment by Fureniku** [comment]
Thanks for reporting - Fixed in 1.0.2 :)
