### ISSUE TITLE
Invisible road/sidewalk blocks

### ISSUE THREAD

**Issue by allenpan11** [Flenix/FlenixRoads#51]
Whenever any block that is not a full block (including ones from other mods) is placed above a road or sidewalk block, the road/sidewalk block turns invisible. Also if a streetlight from any mod including this one is placed, the block(s) below will turn invisible.
![2022-01-18_20 35 31](https://user-images.githubusercontent.com/97998754/150047773-3d681017-d539-4952-9e17-ad975185d24a.png)
![2022-01-18_20 36 02](https://user-images.githubusercontent.com/97998754/150047774-77b3038a-de2d-4b9e-8110-a2f92c7da17f.png)

**Comment by Fureniku** [comment]
Hi,

This was a problem in the 1.1 final build. You can either use the 1.2 beta builds (which have some incomplete creative-only features that can be ignored or experimented with) or an earlier 1.1 build

Thanks
