### ISSUE TITLE
road lines connecting to arrows

### ISSUE THREAD

**Issue by allenpan11** [Flenix/FlenixRoads#53]
Road lines connect to arrow lines when they are placed next to each other. Will there be any fixes for this?
![2022-01-26_20 41 00](https://user-images.githubusercontent.com/97998754/151277211-2ab8d81a-f352-40a1-b9ad-d1105685a615.png)

**Comment by Fureniku** [comment]
This would be a case for using the non-connecting version of the lines (the ones without a blue border). Below shows non connecting on left, and connecting on the right.

![image](https://user-images.githubusercontent.com/856762/236343346-78ad0c46-a043-437e-9c63-e9722da014ac.png)
