### ISSUE TITLE
NEID/JEID causes Unexpected error and corrupts the save

### ISSUE THREAD

**Issue by MarcoGregio** [Flenix/FlenixRoads#54]
1) Added custom paints files in the correct folder (new feature of 1.2)
2) After adding another custom paint, I ran out of block IDs, respecting Forge limits (max 4096 block IDs) (log: crash-2023-05-06_22.18.03-client)
3) Installed the NEID mod to extend the available IDs
4) After loading the client, tried opening my save, where I was trying the custom paints. There were no custom paints blocks in the world as I would break them every time I logged off while I was trying them, however I would always have the paint gun in my hand
5) The game would start loading the world and after a while it would start shutting down the internal server, then crash (log: crash-2023-05-06_22.38.55-client)
6) I uninstalled NEID and all my custom paints files from the modpack, restarted my client and tried opening the same save, it would crash the same way and give a slightly different error, seems caused by the same entity (log: crash-2023-05-07_00.11.36-client)
7) I am unable to reopen the save (without NEID, creating another world doesnt give any error and the game doesnt crash, as expected).

[crash-2023-05-06_22.18.03-client.txt](https://github.com/Fureniku/Furenikus-Roads/files/11413495/crash-2023-05-06_22.18.03-client.txt)
[crash-2023-05-06_22.38.55-client.txt](https://github.com/Fureniku/Furenikus-Roads/files/11413496/crash-2023-05-06_22.38.55-client.txt)
[crash-2023-05-07_00.11.36-client.txt](https://github.com/Fureniku/Furenikus-Roads/files/11413497/crash-2023-05-07_00.11.36-client.txt)

**Comment by Fureniku** [comment]
This was addressed on Discord at the time, forgot to close the issue.
Crash itself was a bug with the paint gun, unrelated to world item IDs and instead the gun GUI was trying to load an ID that didn't exist, because it had been removed.
Added a catch for it, but general rule is to avoid removing blocks or items from your world if at all possible, and that extends to custom paints too.
