### ISSUE TITLE
Item "Clinker Mix" is not able to be pumped into the crusher.

### ISSUE THREAD

**Issue by ViVBling** [Flenix/FlenixRoads#55]
There was no way for me to automatically insert "Clinker Mix" into the Crusher to create "Cement Dust". I've tried different methods starting from the vanilla hopper, modded pipes such as Thermal Dynamics Itemducts, ExtraUtilities Transfer Nodes and Pipes, Mekanism Logistical Transporter or even Buildcraft Pipes. Besides "Clinker Mix" every other Item that can be processed by the Crusher (both types) can be inserted from the back. This issue is still present in Mod Version 1.2.2 for Minecraft 1.12.2.

**Comment by Fureniku** [comment]
Fixed in 1.2.3, which should be available by the end of the weekend
