### ISSUE TITLE
Diagonal connectors disappear on server after restarting

### ISSUE THREAD

**Issue by danmilko** [Flenix/FlenixRoads#56]
Mod version: 1.2.2
Well, the title says much for that. 
When I use this mod on a server, everything is fine until a restart. But after that all diagonal connectors just disappear. Everything else used (lanes, blocks, road parts) is saved correctly.
In singleplayer everything includeing connectors works fine either.

**Comment by Fureniku** [comment]
Fixed in 1.2.3, just testing a few other things and aim to release by the end of the weekend :)
