### ISSUE TITLE
crash after placing down paint

### ISSUE THREAD

**Issue by matejB13** [Flenix/FlenixRoads#58]
after painting some chevrons on a road the game crashed and keeps crashing when i attempt to load the same world.
[crash-2023-08-22_15.49.27-client.txt](https://github.com/Fureniku/Furenikus-Roads/files/12409424/crash-2023-08-22_15.49.27-client.txt)
using game version 1.12.2 and mod version 1.2.2

**Comment by Fureniku** [comment]
Fixed in 1.2.5
