### ISSUE TITLE
Little Paint Gun Bug

### ISSUE THREAD

**Issue by Ryk7039** [Flenix/FlenixRoads#59]
A little paint gun bug: diagonal arrow body and diagonal arrow icons are inverted.
![2023-08-28_21 16 32](https://github.com/Fureniku/Furenikus-Roads/assets/143446017/b06e3128-0346-40f6-8f1c-82ccfdbbc24a)
![2023-08-28_21 16 15](https://github.com/Fureniku/Furenikus-Roads/assets/143446017/0f05a8f8-9f66-4828-b072-ce55e9b769d1)

**Comment by Fureniku** [comment]
Fixed in 1.2.5
