### ISSUE TITLE
[1.12.2][BUG] paint does not render in item frames

### ISSUE THREAD

**Issue by InuYasha86000** [Flenix/FlenixRoads#61]
I know paints used to render in item frames, I used to use letters on buildings, however they do not seem to render in item frames anymore. I am NOT using Optifine. you can see from WAILA in the top that I DID place a ? but there is no image of it in the item frame. I tried with other item frames and nothing still, also other paints and nothing as well.
![2023-09-23_20 22 13](https://github.com/Fureniku/Furenikus-Roads/assets/15805183/a9182af7-ff15-4c4d-bd2c-51acff087c7e)

**Comment by Fureniku** [comment]
I'm not sure I'll be able to look into this, but as a more direct
workaround you can place all letter paints directly on walls anyway

**Comment by Fureniku** [comment]
Closing as this is an issue with FoamFix
