### ISSUE TITLE
[BUG] V1.2.5 for 1.12.2, angle blocks show dirt instead of grass path when placed next to grass path

### ISSUE THREAD

**Issue by InuYasha86000** [Flenix/FlenixRoads#63]
as the comment suggests, when you place an angle block next to a grass path block it does not show as a grass path but as dirt instead. the height is correct but the texture is wrong.
![2023-10-28_19 04 44](https://github.com/Fureniku/Furenikus-Roads/assets/15805183/6c6909cd-ef13-47de-8fc3-3ebb92da4829)

**Comment by Fureniku** [comment]
Fixed in 1.2.6
