### ISSUE TITLE
[CRASH] 1.2.4 Diagonal Road Block Server Crash

### ISSUE THREAD

**Issue by RavenholmZombie** [Flenix/FlenixRoads#64]
[crash-2023-10-31_18.26.44-server.txt](https://github.com/Fureniku/Furenikus-Roads/files/13222041/crash-2023-10-31_18.26.44-server.txt)

Diagonal road blocks are causing our server to crash with a NoSuchMethodError

**Comment by Fureniku** [comment]
Fixed in 1.2.6
