### ISSUE TITLE
Feature: Update the 1.20 (WIP) version to use Architectury

### ISSUE THREAD

**Issue by samuelh2005** [Flenix/FlenixRoads#67]
The [https://github.com/architectury/architectury-api](Architectury API) is an API that allows mod developers to make mods that work on multiple platforms (forge / fabric). This "magic" work by having separate projects for each platform that loads the "common" project. They have [https://github.com/architectury/architectury-templates/releases](templates) to help you get started.

The development of Forge is slowing down, and most of the Forge developers have left and created NeoForge (see [https://neoforged.net/news/theproject/](here) for more details), this creates some uncertainty about Forge / NeoForge's longevity. Meanwhile, Fabric has probably been waiting for this opportunity so more mods can get ported.

In my experience, large modpacks perform better on Fabric then Forge.

Updating the (WIP) 1.20 version to Fabric (using Architectury) would mean more people can use your mod.

**Comment by Fureniku** [comment]
Not going to happen unfortunately, I've ran into compatibility issues with other mods while using mods that depend on architectury. There's still plenty of forge mods in 1.20 and I think neoforge will grow the community, not shrink it, so I'll be staying with neo/forge.
