### ISSUE TITLE
Suggestion:Compatibility other mods

### ISSUE THREAD

**Issue by ym1025** [Flenix/FlenixRoads#7]
Hello! This mod is a great mod,but it's unfinished of compatibility other mods.
1:Tar distiller didn't connect any mod's fluid pipe.
2:Items of this mod isn't registered ore dictionary.
 ex:Limestone,Tar,Coal cake...etc
3:This mod is not support JEI.
4:Machines are not work with RF and FE.
5;Manholes are can't openable.

Thank you for listening.
Sorry,I'm not good at English.

**Comment by Fureniku** [comment]
1. Tar isn't a real fluid currently, in that it has no use outside of my machines. In the future, it will work with piping, but this isn't a priority currently as that's going to be part of a patch for mass production/automation.

2. These things should be registered to the ore dictionary, I'll look into why that's happening.

3. What exactly isn't working with JEI? If you mean machine-specific recipes, then yes. This requires special additional code which isn't a priority for early releases, I'd rather work on getting the mod out so people can use it than delay it to add support for specific things.

4. Correct. The machines run on coal, not electricity.

5. Yes, they are just decorative. Interactions for things will come in future updates but the current manholes will always just be decorative.
